framework:
  workflows:
    absence_state:
      marking_store:
        type: method
        property: state
      supports: App\Entity\Absence
      initial_marking: NONE
      places:
        - NONE
        - ACCEPTED
        - REFUSED
      transitions:
        accept:
          from:
            - NONE
            - REFUSED
          to: ACCEPTED
        refuse:
          from:
            - NONE
            - ACCEPTED
          to: REFUSED

